version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: taegyun93
      POSTGRES_PASSWORD: taegyun93!
      POSTGRES_DB: agent_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    restart: always
    environment:
      ETCD_AUTO_COMPACTION_RETENTION: "1"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/etcd

  minio:
    image: minio/minio:RELEASE.2023-01-12T02-06-16Z
    container_name: minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  milvus:
    image: milvusdb/milvus:v2.3.0
    container_name: milvus
    restart: always
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MILVUS_DEPLOY_MODE: standalone
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  pgdata:
  milvus_data:
  etcd_data:
  minio_data: